// Generated by https://quicktype.io

import { Twit } from "./twit.interface";

export interface User {
  id:               string;
  username:        string;
  nickname:        string;
  description:        string;
  creationAccountDate: Date;
  n_followers:       number;
  n_followed: number;
  profilePicture:      string;
  coverPicture: string;
  twits: Twit[];
  followers: User[];
  email: string;
  password: string;
}


